-- Q1. Registered Customers
-- How many customers are registered on the platform?

select count(id) as registered_customers
from "user" u 

-- Q2. Orders & Revenue
-- How many orders have been placed and what is the total revenue?

select count(id) as total_orders, sum(total) as total_revenue
from order_details od 

-- Q3. Average Order Value
-- What is the average order value?

select avg(total) as avg_order_value
from order_details od 

-- Q4. Highest & Lowest Order
-- What are the highest and lowest order values?

select max(total) as highest_order_amount, min(total) as lowest_order_amount
from order_details od 

-- Q5. Total Products
-- How many products are available in the product table?

select count(id) as total_available_products
from product p 

-- Q6. Total Product Categories
-- How many product categories exist?

select count(id) as total_available_product_categories
from product_category pc 

-- Q7. Total Shopping Sessions
-- How many shopping sessions have been created?

select count(id) as total_shopping_session
from shopping_session ss 

-- Q8. Cart Items & Total Units
-- How many cart-item records do we have,
-- and how many total product units are represented by them?

select count(id) as total_cart_items, sum(quantity) as total_units_in_cart
from cart_item ci 

-- Q9. Successful Payments
-- How many total payments are there,
-- and how many have Completed status?

select count(id) as total_payments, count(case when status = 'Completed' then id end) as completed_payments
from payment_details pd 

-- Q10. Payment Status Breakdown
-- How many payments are there for each payment status?

select status as payment_status, count(id) as count
from payment_details pd 
group by pd.status 

-- Q11. Revenue by Payment Status
-- How much payment amount is associated with each payment status?

select status as payment_status, sum(amount) as total_revenue
from payment_details pd 
group by pd.status 

-- Q12. Orders by Customer
-- Show each customer and the number of orders they have placed.
-- Include customers who have ZERO orders.

select u.id as customer_id, count(od.id) as number_of_orders
from "user" u 
left join order_details od 
on u.id = od.user_id 
group by u.id 
order by customer_id 

-- Q13. Revenue by Customer
-- Show each customer and their total spending.
-- Only customers who have placed orders need to appear.

select u.id as customer_id, sum(od.total) as total_spending
from "user" u 
join order_details od 
on u.id = od.user_id 
group by u.id 
order by u.id 

-- Q14. Products by Category
-- Show each product category and the number of products
-- belonging to that category.

select pc.name as product_category_name, count(p.id) as total_products
from product_category pc 
join product p 
on pc.id = p.category_id 
group by pc."name" 
order by product_category_name 

-- Q15. Average Product Price by Category
-- What is the average product price for each category?

select pc.name as product_category_name, avg(price) as avg_product_category_price
from product_category pc 
join product p 
on pc.id = p.category_id 
group by pc."name" 
order by product_category_name 

-- Q16. Orders Above Average
-- Find all orders whose total is greater than the
-- overall average order value.

with avg_order as (
select id as order_id, user_id, total as order_amount, avg(total) over() as avg_order_amount
from order_details od)
select order_id, user_id, order_amount
from avg_order 
where order_amount > avg_order_amount 

-- Q17. Customers With More Than One Order
-- Find customers who have placed more than one order.

select user_id as customer_id, count(id) as orders
from order_details od 
group by od.user_id 
having count(id)>1

-- Q18. Revenue by Product
-- Calculate the revenue generated by each product.

select oi.product_id, p.name as product_name, sum(((oi.quantity*p.price)*(1-(coalesce(d.discount_percent,0)/100)))) as revenue
from order_items oi 
join product p 
on oi.product_id = p.id 
left join discount d 
on p.discount_id = d.id 
group by oi.product_id, p."name" 
order by revenue desc 

-- Q19. Revenue by Category
-- Calculate the total revenue generated by each product category.

select p.category_id, pc.name, sum(((oi.quantity*p.price)*(1-(coalesce(d.discount_percent,0)/100)))) as revenue
from order_items oi 
join product p 
on oi.product_id = p.id 
join product_category pc 
on p.category_id = pc.id
left join discount d 
on p.discount_id = d.id 
group by p.category_id, pc.name
order by revenue desc 

-- Q20. Cart Conversion Rate
-- Calculate the percentage of shopping sessions
-- that resulted in an order.

select count(ss.id) as total_shopping_sessions, count(od.id) as total_orders, (count(od.id)*100.0)/count(ss.id) as conversion_rate
from shopping_session ss 
left join order_details od 
on ss.id = od.session_id 

-- Q21. Top Customers by Spending
-- Rank customers based on their total spending.

with spendings as (
select user_id as customer_id, sum(total) over(partition by user_id) as total_spendings
from order_details od),
ranked_spendings as (
select customer_id, total_spendings, dense_rank() over(order by total_spendings desc) as spendings_rank
from spendings)
select customer_id, total_spendings
from ranked_spendings 
where spendings_rank <=10

-- Q22. Top 3 Products by Revenue
-- Find the top 3 products based on revenue.
-- If products have the same revenue, they should receive
-- the same ranking.


-- Write your query below:

with product_revenue as (
select oi.product_id, p.name as product_name, sum(((oi.quantity*p.price)*(1-(coalesce(d.discount_percent,0)/100)))) as revenue,
dense_rank() over(order by sum(((oi.quantity*p.price)*(1-(coalesce(d.discount_percent,0)/100)))) desc) as revenue_rank
from order_items oi 
join product p 
on oi.product_id = p.id 
left join discount d 
on p.discount_id = d.id 
group by oi.product_id, p."name" 
order by revenue desc)
select product_id, product_name, revenue
from product_revenue 
where revenue_rank <=3

-- Q23. Highest-Revenue Product in Each Category
-- Find the highest-revenue product within every category.

with o1 as (
select distinct pc.name as category_name, p.name as product_name,
sum(((oi.quantity*p.price)*(1-(coalesce(d.discount_percent,0)/100)))) as product_revenue,
dense_rank() over(partition by pc.name order by sum(((oi.quantity*p.price)*(1-(coalesce(d.discount_percent,0)/100)))) desc) as revenue_rank
from order_items oi 
join product p 
on oi.product_id = p.id 
join product_category pc 
on p.category_id = pc.id
left join discount d 
on p.discount_id = d.id 
group by pc.name, p.name)
select category_name, product_name, product_revenue
from o1
where revenue_rank = 1
order by o1.product_revenue desc 

-- Q24. Customer Order Ranking
-- For each customer, show their orders ranked from
-- highest-value order to lowest-value order.

select user_id as customemr_id, id as order_id, total as order_total, dense_rank() over(partition by user_id order by total desc) as order_rank
from order_details od 
order by customemr_id, order_total desc

-- Q25. First Order for Each Customer
-- Find each customer's first order.

with o1 as (
select user_id as customer_id, id as order_id, created_at, min(created_at) over(partition by user_id) as first_order_date, total
from order_details od)
select customer_id, order_id, first_order_date, total as first_order_total
from o1 
where created_at = first_order_date 

-- Q26. Customers Who Spent More Than Average
-- Find customers whose total spending is greater than
-- the average spending across all customers who placed
-- at least one order.

with total_spendings as (
select distinct user_id as customer_id, sum(total) over(partition by user_id) as order_amount
from order_details od),
avg_order as (
select customer_id, order_amount, avg(order_amount) over() as avg_order_amount
from total_spendings)
select distinct customer_id, order_amount
from avg_order 
where order_amount > avg_order_amount 
order by customer_id 

-- Q27. Running Revenue by Order Date
-- Show each order and the cumulative revenue generated
-- up to that order date.

select id as order_id, created_at as order_date, total as order_total, 
sum(total) over(order by created_at rows between unbounded preceding and current row) as running_revenue
from order_details od 
order by order_id

-- Q28. Previous Order Amount
-- For every order, show the customer's previous order amount.
--

select user_id as customer_id, id as order_id, created_at as order_date, total as order_amount,
lag(total) over(partition by user_id order by created_at) as previous_order_amount
from order_details od 
order by customer_id 

-- Q29. Repeat vs One-Time Customers
-- Classify every customer who has placed at least one order
-- as:
--
-- 'One-Time Customer' → exactly 1 order
-- 'Repeat Customer'   → more than 1 order

select user_id as customer_id, count(id) as number_of_orders, 
case when count(id) = 1 then 'One-Time Customer' when count(id) > 1 then 'Repeat Customer' end as customer_type
from order_details od 
group by od.user_id 
order by customer_id 

-- Q30. Monthly Revenue
-- Calculate total revenue for each month.

select to_char(created_at, 'YYYY-MM') as month, sum(total) as revenue
from order_details od 
group by to_char(created_at, 'YYYY-MM')

-- Q31. CUSTOMER LIFETIME VALUE

select user_id as customer_id, count(id) as number_of_orders, sum(total) as total_spendings, avg(total) as avg_spendings
from order_details od 
group by od.user_id 
order by customer_id 

-- Q32. REPEAT CUSTOMER RATE
-- Calculate the percentage of customers who have placed
-- more than one order.

with calculated as (
select user_id, count(id) as number_of_orders
from order_details od 
group by od.user_id)
select ((count(distinct case when number_of_orders > 1 then user_id end))*100.0)/(count(distinct user_id)) as repeat_customer_rate
from calculated

-- Q33. AVERAGE ORDERS PER CUSTOMER
-- Calculate the average number of orders placed per customer,
-- including customers with zero orders.

select count(distinct od.id)*1.0/count(distinct u.id) as avg_order_per_customer
from "user" u 
left join order_details od 
on u.id = od.user_id 

-- Q34. REVENUE BY MONTH
-- Find monthly:
--   - month
--   - number of orders
--   - total revenue
--   - average order value
-- Sort chronologically.

select to_char(created_at, 'YYYY-MM') as month, count(id) as number_of_orders, sum(total) as total_sales, avg(total) as avg_sales
from order_details od 
group by to_char(created_at, 'YYYY-MM')
order by to_char(created_at, 'YYYY-MM') 

-- Q35. BEST-SELLING PRODUCTS
-- Find the top 5 products by quantity sold.
--   - product_id
--   - product name
--   - quantity sold
--   - revenue generated

select oi.product_id, p.name as product_name, sum(oi.quantity) as quantity_sold,
(p.price*sum(oi.quantity))*(1-coalesce(d.discount_percent,0)*0.01) as total_revenue_generated_after_discount
from order_details od 
join order_items oi 
on od.id = oi.order_id 
join product p 
on oi.product_id = p.id 
left join discount d 
on p.discount_id = d.id 
group by oi.product_id, p."name", p.price, d.discount_percent 
order by total_revenue_generated_after_discount desc
limit 5

-- Q36. CATEGORY PERFORMANCE
-- For each product category, show:
--   - category name
--   - number of products
--   - quantity sold
--   - total revenue

with product_category_details as (
select pc.id, pc.name, count(p.id) as number_of_products, coalesce(sum(oi.quantity), 0) as quantity_sold
from product_category pc 
left join product p 
on pc.id = p.category_id 
left join order_items oi 
on p.id = oi.product_id 
group by pc."name", pc.id),
product_revenue_details as (
select p.id, p.category_id, (p.price*sum(oi.quantity))*(1-coalesce(d.discount_percent,0)*0.01) as total_revenue_generated_after_discount
from product p 
left join discount d 
on p.discount_id = d.id
left join order_items oi 
on p.id = oi.product_id 
group by p.id, p.category_id, p.price, d.discount_percent)
select name as category_name, number_of_products, quantity_sold, coalesce(sum(total_revenue_generated_after_discount), 0) as total_revenue_generated_after_discount
from product_category_details pc
left join product_revenue_details pr
on pc.id = pr.category_id 
group by name, number_of_products, quantity_sold 
order by total_revenue_generated_after_discount desc 

-- Q37. PAYMENT SUCCESS RATE
-- Calculate the percentage of payments that are 'Completed'.

select (count(case when status = 'Completed' then id end)*100.0)/(count(id)) as payment_success_rate
from payment_details pd 

-- Q38. CART ABANDONMENT RATE
-- Calculate the percentage of shopping sessions that
-- did NOT result in an order.

select (100.0)-(count(od.session_id)*100.0)/count(ss.id) as total_aboandoned_shopping_sessions
from order_details od 
right join shopping_session ss 
on od.session_id = ss.id 

-- Q39. CUSTOMER ORDER FREQUENCY
-- Classify customers into:
--   - 'One-Time' → exactly 1 order
--   - 'Repeat'   → 2+ orders
--   - 'No Orders' → 0 orders

select u.id as customer_id, count(od.id) as order_count, 
case when count(od.id) = 1 then 'One-Time' when count(od.id) > 1 then 'Repeat' when count(od.id) = 0 then 'No Orders' end as customer_type
from "user" u 
left join order_details od 
on u.id = od.user_id 
group by u.id 
order by customer_id

-- Q40. TOP CUSTOMERS BY REVENUE CONTRIBUTION
-- Find the top 10 customers by total spending.
-- Show:
--   - customer_id
--   - total spending
--   - percentage of total company revenue

select distinct user_id as customer_id, sum(total) over(partition by user_id) as total_spending, 
((sum(total) over(partition by user_id))*100.0)/(sum(total) over()) as percentage_of_total_company_revenue 
from order_details od 
order by percentage_of_total_company_revenue desc
limit 10

-- Q41. INACTIVE CUSTOMERS
-- Find customers who have placed at least one order but
-- have NOT placed an order in the most recent 30 days
-- relative to the latest order date in the database.

with calculated as (
select distinct user_id as customer_id, max(to_char(created_at, 'YYYY-MM-DD')) over(partition by user_id) as latest_order_date_of_customer,
max(to_char(created_at, 'YYYY-MM-DD')) over() as lastest_order_date_at_store
from order_details od)
select customer_id, latest_order_date_of_customer
from calculated 
where to_date(lastest_order_date_at_store, 'YYYY-MM-DD') - to_date(latest_order_date_of_customer, 'YYYY-MM-DD') > 30
order by latest_order_date_of_customer desc 

-- ============================================================


-- Q42. HIGHEST-VALUE ORDER PER CUSTOMER
-- Find the highest-value order placed by each customer.
--
-- Show:
--   customer_id
--   order_id
--   order_amount
--
-- If a customer has multiple orders with the same highest
-- amount, return only ONE order.


-- Write your query below:





-- ============================================================


-- Q43. CUSTOMERS WHO INCREASED THEIR SPENDING
-- Find customers whose most recent order was greater in
-- value than their previous order.
--
-- Show:
--   customer_id
--   previous_order_amount
--   latest_order_amount
--
-- Only include customers who have at least 2 orders.


-- Write your query below:





-- ============================================================


-- Q44. PRODUCT SALES CONTRIBUTION
-- For every product, calculate its percentage contribution
-- to total company revenue.
--
-- Show:
--   product_id
--   product_name
--   product_revenue
--   revenue_contribution_percentage
--
-- Sort by revenue contribution descending.


-- Write your query below:





-- ============================================================


-- Q45. CATEGORY REVENUE RANKING
-- Rank product categories based on total revenue.
--
-- Show:
--   category_name
--   total_revenue
--   revenue_rank
--
-- Categories with the same revenue should receive the
-- same rank.


-- Write your query below:





-- ============================================================


-- Q46. MONTH-OVER-MONTH REVENUE GROWTH
-- Calculate monthly revenue and the percentage change
-- compared with the previous month.
--
-- Show:
--   month
--   monthly_revenue
--   previous_month_revenue
--   revenue_growth_percentage
--
-- The first month can have NULL for previous revenue
-- and growth percentage.


-- Write your query below:





-- ============================================================


-- Q47. TOP CUSTOMER IN EACH MONTH
-- Find the customer who generated the highest revenue
-- in each month.
--
-- Show:
--   month
--   customer_id
--   total_revenue
--
-- If multiple customers tie for the highest revenue,
-- return only ONE customer.


-- Write your query below:





-- ============================================================


-- Q48. ABANDONED CART VALUE
-- Calculate the total potential value of products that
-- remained in shopping sessions that were NOT converted
-- into orders.
--
-- Show:
--   abandoned_session_count
--   abandoned_cart_value
--
-- Use product price and quantity.
-- Apply the product discount where applicable.


-- Write your query below:





-- ============================================================


-- Q49. REPEAT CUSTOMER REVENUE
-- Compare revenue generated by:
--   - One-Time customers
--   - Repeat customers
--
-- Show:
--   customer_type
--   number_of_customers
--   total_revenue
--   percentage_of_total_revenue
--
-- Do NOT include customers with zero orders.


-- Write your query below:





-- ============================================================


-- Q50. CUSTOMER REVENUE SEGMENTATION
-- Classify customers based on their total spending:
--
--   High Value   → spending >= 75th percentile
--   Medium Value → spending >= 25th percentile
--                    and below 75th percentile
--   Low Value    → spending < 25th percentile
--
-- Show:
--   customer_id
--   total_spending
--   customer_segment
--
-- Only include customers who have placed at least one order.


-- Write your query below:





-- ============================================================
-- END OF SQL PROJECT ANALYSIS
--
-- After Q50:
--   1. Select final KPIs
--   2. Build Power BI dashboard
--   3. Add business insights
--   4. Prepare GitHub repository
--   5. Update LinkedIn
--   6. SQL revision + HackerRank SQL Advanced
-- ============================================================